import { Inter } from "next/font/google";
import "./globals.css";
//import components
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import ScrollButton from "@/components/ScrollButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Elmur",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          " w-screen overflow-x-hidden bg-black text-white scroll-smooth"
        }
      >
        <NavBar />
        {children}
        <ScrollButton />
        <Footer />
      </body>
    </html>
  );
}
