import { Inter } from "next/font/google";
import "./globals.css";
//import components
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import ScrollButton from "@/components/ScrollButton";

import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { routing } from "@/i18n/routing";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Elmur",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;
  const messages = await getMessages();

  return (
    <html lang="en">
      <body
        className={
          inter.className +
          " w-screen overflow-x-hidden bg-black text-white scroll-smooth"
        }
      >
        <NextIntlClientProvider messages={messages}>
          <NavBar locale={locale} />
          {children}
          <ScrollButton />
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
